### PR TITLE
Correct DataSetTrimTest.testTrimGroup

### PR DESCRIPTION
**Pull request by nothinginteresting**
COLUMN_CITY should not be used here

### CODE REVIEW

**Comment by dgutierr** [comment]
Adding non aggregated columns to a grouped dataset will add the column's first available value for each group row.  Also the test is working fine. 

@nothinginteresting Is there anything wrong you want to point out?

**Comment by nothinginteresting** [comment]
You are right. But I can not understand why

SELECT city AS "CITY", department AS "DEPARTMENT", SUM(amount) AS "AMOUNT_sum" FROM expense_reports GROUP BY department, city LIMIT 10

produces only 5 rows.

**Comment by dgutierr** [comment]
@nothinginteresting The SQL you posted will probably produce more rows since it is actually grouping by city & dept.  

On the other hand, this data lookup request it is only grouped by department.

DataSetLookupFactory.newDataSetLookupBuilder()
                          .dataset(EXPENSE_REPORTS)
                          .group(COLUMN_DEPARTMENT)
                          .column(COLUMN_CITY)
                          .column(COLUMN_DEPARTMENT)
                          .column(COLUMN_AMOUNT, AggregateFunctionType.SUM)
                          .rowNumber(10)
                          .buildLookup());

 The processing of this data lookup implies the execution of the SQL you mention but also a post-processing of the results in order to ensure the resulting dataset is grouped by dept only.

**Comment by nothinginteresting** [comment]
Thank you for your explanation.
I found SQLDatasetProvider with postProcessing flag.
The Truth Is Out There.

**Pull request closed without merging**
