### PR TITLE
[GUVNOR-2882] Rename Tomcat 8 WAR, tomcat7 -> tomcat8

### PR DESCRIPTION
**Pull request by psiroky**

### CODE REVIEW

**Comment by psiroky** [comment]
@manstis could please quickly check this one as well? I know dashbuilder is not your primary responsibility, but you what is going since you already reviewed the other Tomcat PRs :)

**Comment by manstis** [comment]
@psiroky I don't have permission to merge.. you'll probably need @dgutierr for that.

**Comment by psiroky** [comment]
Thanks Mike! @dgutierr or @romartin could you please merge this?

**Comment by romartin** [comment]
Merged: eaae9c4c9f974c8af0f98c97de35f3d571d41878

Thanks @psiroky , @manstis !

**Pull request closed without merging**
