### PR TITLE
DASHBUILDE-258: Displayer filter labels sometimes cannot be closed

### PR DESCRIPTION
**Pull request by dgutierr**
Fix + test.

@romartin Can you approve & merge please?

### CODE REVIEW

**Comment by jhrcek** [comment]
@romartin @dgutierr please let me verify this before merging. I'll provide feedback today.

**Comment by jhrcek** [comment]
Jenkins execute full downstream build

**Comment by klarakufova** [comment]
@dgutierr 
I noticed the same issue in the Team Metrics dashboard, but I couldn't reproduce it, so I didn't file a Jira. Will this PR fix also the Metrics dashboards?

**Comment by kkufova** [comment]
@dgutierr
I noticed the same issue in the Team Metrics dashboard, but I couldn't reproduce it, so I didn't file a Jira. Will this PR fix also the Metrics dashboards?

**Comment by dgutierr** [comment]
@kkufova Yes, it will. The issue happens at any dashboard where there are multiple filter interaction between two or more displayers. I was able to reproduce it in the metrics dashboard as well.

**Pull request merged**
