### PR TITLE
UF-267: Perspective editor column is blocked after a component is added and closed

### PR DESCRIPTION
**Pull request by paulovmr**

### CODE REVIEW

**Comment by paulovmr** [comment]
jenkins retest this

**Comment by paulovmr** [comment]
Hi @dgutierr, I don't think this PR has to do with the test failure. Could you take a look? (I did the same modifications on master and the build passed: https://github.com/dashbuilder/dashbuilder/pull/115)

**Comment by psiroky** [comment]
Test failure not related to this PR. The test was fixed on master, but not on 0.4.x. I've created https://github.com/dashbuilder/dashbuilder/pull/117 for that.

**Comment by paulovmr** [comment]
Thanks, @psiroky!

**Comment by dgutierr** [comment]
+1 @csadilek  can you please merge all the related PRs togheter, once they are approved?

**Comment by paulovmr** [comment]
@dgutierr @csadilek Actually the other PRs are already merged, I only had missed the Dashbuilder's displayer component.

**Comment by csadilek** [comment]
0.4.x: d1583455b4fedf11fd23e52bc2624990623fb418

**Pull request closed without merging**
