### PR TITLE
squid:UselessParenthesesCheck - Useless parentheses around expressions should be removed to prevent any misunderstanding

### PR DESCRIPTION
**Pull request by georgekankava**
This pull request is focused on resolving occurrences of Sonar rule
squid:UselessParenthesesCheck - Useless parentheses around expressions should be removed to prevent any misunderstanding.
You can find more information about the issue here:
https://dev.eclipse.org/sonar/coding_rules#q=squid%3AUselessParenthesesCheck
Please let me know if you have any questions.
George Kankava

### CODE REVIEW

**Comment by psiroky** [comment]
Thanks @georgekankava. Would it be possible to squash the commits into single one?

**Comment by georgekankava** [comment]
I tried it but got mix of old rule and this new rule.

**Comment by dgutierr** [comment]
@georgekankava Only one commit should be pushed. I think you need to rebase remote/master and squash if needed.

**Comment by georgekankava** [comment]
I Will resubmit this pull request.

**Pull request closed without merging**
