### PR TITLE
DASHBUILDE-165: Issues with sample Metric displayers in Displayer editor

### PR DESCRIPTION
**Pull request by dgutierr**
Fix + test

@romartin Can you verify & merge please?

### CODE REVIEW

**Comment by romartin** [comment]
Hi @dgutierr , I have problems running the wildfly distribution.  

On the gallery, the two first meter examples are failing with this error "java.lang.RuntimeException: Data set not found: salesOpportunities"

Going to data sets perspective, no data sets found, so it seems that they're not being deployed or there is some error on the deploy.... but not exceptions on the server logs.

Can you please double check if it happens for you? Thanks!

**Comment by dgutierr** [comment]
@romartin Please, check that the ".deploy" files exists in the datasets deployments directory. Otherwise, datasets are not deployed.

**Comment by romartin** [comment]
@dgutierr you're who are removed those deploy files... why??  See https://github.com/dgutierr/dashbuilder/tree/DASHBUILDE-165/dashbuilder-webapp/src/main/webapp/WEB-INF/datasets

**Comment by dgutierr** [comment]
@romartin Good catch! I removed them by error. Now it should be fine.

**Comment by romartin** [comment]
Closed: 89d0d6474d8b882765762a595c8e5c13f9e4a3cd

**Pull request closed without merging**
