### PR TITLE
upgraded 0.3.x to latest jboss-ip-bom 6.0.0.CR30

### PR DESCRIPTION
**Pull request by mbiarnes**

### CODE REVIEW

**Comment by psiroky** [comment]
+1 to merge once the build succeeds.

**Comment by mbiarnes** [comment]
I did test on my local with executing tests and it worked???

**Comment by psiroky** [comment]
@dgutierr could you please take a look and merge this one? Test failures are not related to the changes in this PR (I am still investigating the root cause of those failures)

**Comment by dgutierr** [comment]
Merged on 0.3.x

**Pull request closed without merging**
