### PR TITLE
DASHBUILDE-218: Visually distinguish modifiable / unmodifiable items in NavTreeEditor

### PR DESCRIPTION
**Pull request by dgutierr**
Implementation done => https://issues.jboss.org/secure/attachment/12420568/dashbuilder_navitem_actions3.mp4

@romartin @jhrcek Can you review please?

### CODE REVIEW

**Comment by jhrcek** [comment]
@dgutierr looks nice. I'll review this first thing on monday and let you know

**Comment by dgutierr** [comment]
@jhrcek Fixed the issues you mention. Also added a few other improvements:

1.- Current item edition is cancelled if another item's edition is started.
2.- Empty names are not allowed (name input box is marked as red).
3.- Changes must always be confirmed by clicking on the proper icon.

Please have a look => https://issues.jboss.org/secure/attachment/12420640/12420640_dashbuilder_navitem_actions4.mp4

**Comment by jhrcek** [comment]
Thanks for quict fixes! I tried it locally with dashbuilder-showcase where it works fine. I'd still like to run selenium tests which only work with kie-wb, but I was unable to build this locally.

I'll let Jenkins execute full downstream build and check the war tomorrow morning. Please wait with the merge.

**Comment by jhrcek** [comment]
@dgutierr it seems that the downstream build job is failing with the same [error](http://lpaste.net/355956) that I was getting when building kie-wb locally (first `mvn clean install` in dashbuilder with this PR checked out (successfully) and then the `mvn clean install` in kie-wb-distributions which fails). Any idea what might be wrong?

**Comment by jhrcek** [comment]
Jenkins execute full downstream build

**Comment by jhrcek** [comment]
Tested locally and almost all the issues have been fixed now except for this last thing:

The buttons still overlap in the NavItemEditor "edit mode" 
editmodeoverlap

**Comment by dgutierr** [comment]
@jhrcek Latest issue fixed.

**Comment by dgutierr** [comment]
@romartin merge? :-)

**Comment by jhrcek** [comment]
Jenkins please test this

**Comment by jhrcek** [comment]
@romartin ready for merge :)

**Comment by romartin** [comment]
Merged: e8d722e49e137c9ed8dc45e5c1a52f0471cd291a

**Pull request closed without merging**
