### PR TITLE
Added IN and NOT_IN function for data set filtering

### PR DESCRIPTION
**Pull request by mswiderski**
@dgutierr please have a look ... and let me know what's missing :)

### CODE REVIEW

**Comment by dgutierr** [comment]
It looks perfect!

The missing bits are the following:

1. ElasticSearch support

Add support for the IN and NOT IN functions just as they were EQUALS and NOT EQUALS functions: 

ElasticSearchQueryBuilderImpl::380

        if (CoreFunctionType.IN.equals(type)) {
            type = CoreFunctionType.EQUALS_TO;    
        }
        if (CoreFunctionType.NOT_IN.equals(type)) {
            type = CoreFunctionType.NOT_EQUALS_TO;    
        }

.. and also make sure the tests are added to the ELS suite:

ElasticSearchCommonTests::79

        subTest.testInOperator();
        subTest.testNotInOperator();

2. SQL constructs in uppercase

To be consistent with the whole SQL generation nomenclature

DefaultDialect::480

        inStatement.append(" IN (");

3. CoreFunctionFilter::80

Add the toString representation. Basically, for better feedback while debugging lookup calls.

4. Make the UI work well with the new functions

CoreFunctionTypeConstants.properties

         IN=in
         NOT_IN=not in

ColumnFilterEditor::354
         
        else if (CoreFunctionType.IN.equals(type)) {
            out.append(columnId).append(" in (");
            formatParameters(out, parameters);
            out.append(")");
        }
        else if (CoreFunctionType.NOT_IN.equals(type)) {
            out.append(columnId).append(" not in (");
            formatParameters(out, parameters);
            out.append(")");
        }

5. Commit message

I've created a JIRA for this specific feature so that we can link the commit message with the JIRA https://issues.jboss.org/browse/DASHBUILDE-85


That's all.

**Comment by mswiderski** [comment]
cool, thanks for feedback. Will add the missing bits and update PR - today :)

**Comment by mswiderski** [comment]
@dgutierr all updates are now applied, please have a look

**Comment by dgutierr** [comment]
+1 

I've also added the required changes to allow for the creation of new functions in the filter editor UI.

Thanks a lot @mswiderski

**Pull request closed without merging**
