### PR TITLE
Upgrade to final GWT 2.8.0

### PR DESCRIPTION
**Pull request by csadilek**
@dgutierr

### CODE REVIEW

**Comment by dgutierr** [comment]
I'm getting an error while trying to execute from command line  "mvn gwt:run"

[INFO] --- gwt-maven-plugin:2.8.0:run (default-cli) @ dashbuilder-webapp ---
[INFO] create exploded Jetty webapp in /home/dgutierr/Devel/git/dashbuilder/dashbuilder/dashbuilder-webapp/src/main/webapp
[INFO] Super Dev Mode starting up
[INFO]    workDir: /tmp/gwt-codeserver-5414296489078017909.tmp
[INFO]    Loading Java files in org.dashbuilder.FastCompiledDashbuilderShowcase.
[INFO]    Ignored 3 units with compilation errors in first pass.
[INFO] Compile with -strict or with -logLevel set to DEBUG or WARN to see all errors.
[INFO]    Module setup completed in 23456 ms
[INFO] 
[INFO] The code server is ready at http://127.0.0.1:9876/
[INFO] Warning! The CLI is running in a non-modular environment and cannot load commands from management extensions.
[ERROR] Unable to start embedded HTTP server
[ERROR] com.google.gwt.core.ext.UnableToCompleteException: (see previous log entries)
[ERROR] 	at org.jboss.errai.cdi.server.gwt.EmbeddedWildFlyLauncher.start(EmbeddedWildFlyLauncher.java:113)
[ERROR] 	at com.google.gwt.dev.DevMode.doStartUpServer(DevMode.java:634)
[ERROR] 	at com.google.gwt.dev.DevModeBase.startUp(DevModeBase.java:923)
[ERROR] 	at com.google.gwt.dev.DevModeBase.run(DevModeBase.java:706)
[ERROR] 	at com.google.gwt.dev.DevMode.main(DevMode.java:430)

@csadilek is there anything I'm missing? :-)

**Comment by csadilek** [comment]
@dgutierr please run mvn clean gwt:run and share the full log / stack trace. The fact that the server is not starting up is not related to this upgrade. Maybe you had another (stale) instance running? Starting up fine here on two different machines...

**Comment by romartin** [comment]
Hey @csadilek , @dgutierr ,it works fine -> +1
@dgutierr you have to use the "clean" goal as well when running SDM, as the previous built generate some assets that have to be clean and are rebuilt once on the process-resources phase. So just running "mvn clean gwt:run" works fine. Thanks guys

**Comment by romartin** [comment]
Closed: 8b19baef56fcdf6f4097d6646dc4efa66880eef4

**Pull request closed without merging**
