### PR TITLE
DASHBUILDE-66: NPE data set lookup contains a function with no args

### PR DESCRIPTION
**Pull request by dgutierr**

### CODE REVIEW

**Comment by nmirasch** [comment]
+1 Reviewed Tested the console dataset queries.

**Comment by porcelli** [comment]
-1 i think this is missing some tests for the changes. one example: test equals

**Comment by porcelli** [comment]
+1

**Comment by porcelli** [comment]
failing tests https://gist.github.com/porcelli/dce02febedc691fa7b42

**Comment by porcelli** [comment]
https://github.com/dashbuilder/dashbuilder/commit/2a4aacff45d5387a3fa50529838243e5b8cf7325

**Pull request closed without merging**
