### PR TITLE
UI related fixes (0.6.x)

### PR DESCRIPTION
**Pull request by dgutierr**
Fixes and their corresponding tests.

@romartin Can you please review & merge?

### CODE REVIEW

**Comment by jhrcek** [comment]
@romartin @dgutierr please don't merge till moday. I'll try the fixes locally and provide feedback.

**Comment by romartin** [comment]
Merged:
238e551cded8b534f92ff34a674e0a164d902b70
60439655afb56f8e53304bd917586b44c253e3f7
fd11c87f8432f4baa722193ef1d199ba68021507
bb85013e4f5b49ba4cb43c12392e36f69bd8f16e

**Comment by romartin** [comment]
oh @jhrcek !!!!! just seen the comment nowwwww!!! sorry! argh!! lemme know if any issues please, anyway I tested the dashbuilder webapp and the whole kie-wb and it seems to work... :(
Sorry again , just looked at the mails received and forgot last comment.
CC @dgutierr ^^

**Comment by jhrcek** [comment]
@romartin You are lucky, I tried the PR locally and everything works fine, I didn't find any issues. @dgutierr Thanks for the fixes

**Pull request closed without merging**
