### PR TITLE
DASHBUILDE-96: DB2 does not always support the LIMIT clause (0.4.x)

### PR DESCRIPTION
**Pull request by dgutierr**
The SQL provider test suite has been executed successfully on DB2 9.7 and 10.5 so there is no need for extra tests in this case.

### CODE REVIEW

**Comment by cristianonicolai** [comment]
Tested on DB2 version 9.7 and works fine. Missing only tests in here.
@dgutierr I created a simple test class that should cover what is needed here: https://github.com/dgutierr/dashbuilder/pull/3

**Comment by dgutierr** [comment]
Yeah! that's a good test to guarantee the SQL generated is as expected.

I do not actually provide those kind of tests since I prefer to rely on the
existing integration tests which guarantee that the query not only valid
 but also executes and gets the expected results from the real DB.

Thanks for the PR :-)

- David -

On Fri, Mar 4, 2016 at 10:27 AM, Cristiano Nicolai <notifications@github.com

**Comment by cristianonicolai** [comment]
Sure, specially talking about database, integration tests are the most effective way to ensure it all works. This kind of test from my perspective is just a unit test, aiming to verify that the specific method does what is expected based on different inputs. One doesn't exclude the other, the more we cover our code with tests the better.

**Comment by dgutierr** [comment]
+1

**Comment by romartin** [comment]
+1

**Pull request closed without merging**
