### PR TITLE
DASHBUILDE-102: Upgrade dashbuilder-validations to use Errai Validation

### PR DESCRIPTION
**Pull request by pefernan**
Dashbuilder was overriding GWT validation instead of using errai-validation. That was causing issues on kie-wb when other components where trying to user Validations.

### CODE REVIEW

**Comment by pefernan** [comment]
@dgutierr @romartin can you review it?

**Comment by dgutierr** [comment]
@romartin Can you please take a look since you know far better than me how this stuff works?

**Comment by romartin** [comment]
Hey @pefernan ! Nice job! This was in fact a missing task I had in mind... so thanks! :)
@dgutierr should be good to create a JIRA to review the different error messages that appear for the validations, it's not urgent but should be good.

**Comment by romartin** [comment]
Closed: ff4b356db59f8c7273d951376f3f46a50a297ce8

**Comment by romartin** [comment]
@dgutierr @pefernan  Hey guys, didn't realized that this has to be merged with [this](https://github.com/droolsjbpm/kie-wb-distributions/pull/413). So reverted using [this commit](https://github.com/dashbuilder/dashbuilder/commit/da54844ce8a02e01a23001083dbefc911306db4d) until both can be merged at same time. Sorry for the inconveniences.

**Pull request closed without merging**
