### PR TITLE
DASHBUILDE-95: TableDisplayer filter throws an IllegalArgumentException

### PR DESCRIPTION
**Pull request by dgutierr**

### CODE REVIEW

**Comment by dgutierr** [comment]
@psiroky The build is failing. It seems something related with jenkins conf. Can you review please?

**Comment by dgutierr** [comment]
@romartin Can you review & merge on 0.3.x please?. Deadline is tomorrow EOD.

**Comment by psiroky** [comment]
@dgutierr I've created https://github.com/dashbuilder/dashbuilder/pull/145 which in turn fixes this build (we basically need the number GWT workers configurable so that we can use slaves with "just" 8GB of RAM).

**Comment by romartin** [comment]
done +1

**Pull request closed without merging**
