### PR TITLE
DASHBUILDE-48: MVP & Unit testing

### PR DESCRIPTION
**Pull request by dgutierr**
This PR it's a refactor of the UI layer in order to comply with the MVP best practices. In a nutshell:

* Ensure all UI components follow the MVP (Model View Presenter) pattern in order to ensure a clear separation between "the view", "the presenter" and "the model".

* In such model, The presenter must not contain any widget reference and the model must not "touch" the view as well. The presenter must provide the required logic to pass & update the view with the required information. 

* MVP applicability ensures the logic in the presenter can be properly tested using junit/mockito tests. Along with the refactor several unit tests over the presenter components are provided.

### CODE REVIEW

**Comment by romartin** [comment]
When creating a new dashboard, the contextual menu item for creating new dispalyers does not appear, so i cannot test the mvp refactor for the displayer widget, will try to fix it np

**Comment by dgutierr** [comment]
This might be or not a side-effect issue of the refactor. As a work-around, you can test the Displayer editor from the Perspective editor.

**Comment by dgutierr** [comment]
The contextual menu issue has nothing to do with the changes in this PR since it's also failing on master right now.  @romartin Please do file a JIRA.

**Comment by romartin** [comment]
Please, two issues to review:
- Gallery tree does not appear
- Contextual menu for new perspectives does not appear

**Comment by dgutierr** [comment]
* The gallery tree does not seem an issue. Verified on a fresh installation.
* The contextual menu issue has been reported: https://issues.jboss.org/browse/DASHBUILDE-82

**Comment by romartin** [comment]
Tested again. +1

**Comment by romartin** [comment]
Tested the two other PR that depend on this one:
- The one from jbpm-console is now working in SDM, please see the PR link
- The one from kie-wb-common works fine, please see the PR link

So let's wait for the +1 on jbpm-console-ng's PR...

**Comment by romartin** [comment]
Added +1 on the jbpm-console's PR, as the issue is not produced by this refactor. 

+1 All three PR can be merged

**Comment by csadilek** [comment]
+1

**Comment by csadilek** [comment]
Thanks.

master: 4277c03e16c165585514aa863b842718ca7d406d

**Pull request closed without merging**
