### PR TITLE
DASHBUILDE-157: Metric displayer based on HTML templates

### PR DESCRIPTION
**Pull request by dgutierr**
Implementation of https://issues.jboss.org/browse/DASHBUILDE-157

Tests included.

@romartin Can you review & merge please?

### CODE REVIEW

**Comment by romartin** [comment]
Hi @dgutierr , there is an enforcer error: INFO] 
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-direct-dependencies) @ dashbuilder-displayer-client ---
[INFO] Flag 'useClassesFromLastBuild' is set. Try to use existing output folder.
[INFO] Analyze dependencies of artifact 'org.dashbuilder:dashbuilder-displayer-client:jar:0.6.0-SNAPSHOT'.
[WARNING] Rule 0: de.is24.maven.enforcer.rules.IllegalTransitiveDependencyCheck failed with message:
Found 3 illegal transitive type dependencies in artifact 'org.dashbuilder:dashbuilder-displayer-client:jar:0.6.0-SNAPSHOT':
1.) org.jboss.errai.ui.shared.api.annotations.DataField
2.) org.jboss.errai.ui.shared.api.annotations.EventHandler
3.) org.jboss.errai.ui.shared.api.annotations.Templated

Fixing it and will continue the merge, if it's ok, will push ithe commits.

**Comment by romartin** [comment]
After fixing the maven enforcer issue... tests failed :( Please can you review?

Running org.dashbuilder.renderer.client.table.TableDisplayerTest
Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.435 sec - in org.dashbuilder.renderer.client.table.TableDisplayerTest
Running org.dashbuilder.renderer.client.selector.SelectorDisplayerTest
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.064 sec - in org.dashbuilder.renderer.client.selector.SelectorDisplayerTest
Running org.dashbuilder.renderer.client.metric.MetricDisplayerTest
Tests run: 5, Failures: 0, Errors: 5, Skipped: 0, Time elapsed: 0.049 sec <<< FAILURE! - in org.dashbuilder.renderer.client.metric.MetricDisplayerTest
testSwitchOnFilter(org.dashbuilder.renderer.client.metric.MetricDisplayerTest)  Time elapsed: 0.027 sec  <<< ERROR!
java.lang.NoClassDefFoundError: com/google/gwt/thirdparty/guava/common/base/Preconditions
	at org.dashbuilder.renderer.client.metric.MetricDisplayerTest.testSwitchOnFilter(MetricDisplayerTest.java:145)
Caused by: java.lang.ClassNotFoundException: com.google.gwt.thirdparty.guava.common.base.Preconditions
	at org.dashbuilder.renderer.client.metric.MetricDisplayerTest.testSwitchOnFilter(MetricDisplayerTest.java:145)

testDraw(org.dashbuilder.renderer.client.metric.MetricDisplayerTest)  Time elapsed: 0.004 sec  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class com.google.gwt.thirdparty.streamhtmlparser.HtmlParserFactory
	at org.dashbuilder.renderer.client.metric.MetricDisplayerTest.testDraw(MetricDisplayerTest.java:78)

testSwitchOffFilter(org.dashbuilder.renderer.client.metric.MetricDisplayerTest)  Time elapsed: 0.001 sec  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class com.google.gwt.thirdparty.streamhtmlparser.HtmlParserFactory
	at org.dashbuilder.renderer.client.metric.MetricDisplayerTest.testSwitchOffFilter(MetricDisplayerTest.java:165)

testNoFilter(org.dashbuilder.renderer.client.metric.MetricDisplayerTest)  Time elapsed: 0.003 sec  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class com.google.gwt.thirdparty.streamhtmlparser.HtmlParserFactory
	at org.dashbuilder.renderer.client.metric.MetricDisplayerTest.testNoFilter(MetricDisplayerTest.java:125)

testNoData(org.dashbuilder.renderer.client.metric.MetricDisplayerTest)  Time elapsed: 0.003 sec  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class com.google.gwt.thirdparty.streamhtmlparser.HtmlParserFactory
	at org.dashbuilder.renderer.client.metric.MetricDisplayerTest.testNoData(MetricDisplayerTest.java:105)


Results :

Tests in error: 
  MetricDisplayerTest.testDraw:78 » NoClassDefFound Could not initialize class c...
  MetricDisplayerTest.testNoData:105 » NoClassDefFound Could not initialize clas...
  MetricDisplayerTest.testNoFilter:125 » NoClassDefFound Could not initialize cl...
  MetricDisplayerTest.testSwitchOffFilter:165 » NoClassDefFound Could not initia...
  MetricDisplayerTest.testSwitchOnFilter:145 » NoClassDefFound com/google/gwt/th...

**Comment by dgutierr** [comment]
@roger The issues you mentioned are fixed. Can you give it another try please?

**Comment by romartin** [comment]
Hi @dgutierr , the build and tests are fine but I found an issue running the webapp (on Wildfly10). 

Creating a new metric displayer seems to work fine and really like the new stuff!! But the metric examples on the gallery are not working, nothing appears on those screens, no error on console at first glance.. but after some clicks ( back to gallery screen then back to the metrics example screen etc ) an error on the browser console appears. It does not happens when navigating to other gallery example screens, only after visiting the metrics one..

Can you please take a look at this before merging? Quite sure there is an error yet... :) 

Will wait for merge until getting your feedback!

**Comment by dgutierr** [comment]
@romartin Fixed the gallery as well!

**Comment by romartin** [comment]
Good :)
Closed: 0a97610ad6fea2f69ca3615580f50e4aac943533

**Pull request closed without merging**
