### PR TITLE
ERRAI-1042: Moving ErraiApp.properties to META-INF dir

### PR DESCRIPTION
**Pull request by tiagobento**
https://issues.jboss.org/browse/ERRAI-1042

### CODE REVIEW

**Comment by tiagobento** [comment]
jenkins retest this please

**Comment by tiagobento** [comment]
jenkins retest this please

**Comment by tiagobento** [comment]
jenkins retest this please

**Comment by tiagobento** [comment]
jenkins retest this please

**Comment by tiagobento** [comment]
jenkins retest this please

**Comment by manstis** [comment]
Jenkins please execute full downstream build.

**Comment by tiagobento** [comment]
@manstis Could you merge this? Thanks!

**Comment by manstis** [comment]
@tiagobento I'd love to, but I don't have permission for this repository.

IDK whether @mbiarnes or @psiroky do!?!

**Comment by psiroky** [comment]
I do, but I wish I didn't :)

**Pull request merged**
