### PR TITLE
Update SingletonBeanDef usage to match upstream API change.

### PR DESCRIPTION
**Pull request by mbarkley**
This PR should stay open until @psiroky is able to add Errai to the Jenkins job that tests PRs.

This updates usage of the SyncBeanDef interface updated in [this PR](https://github.com/errai/errai/pull/161). At present the Jenkins job that builds this PR will fail because it does not build the changes from the Errai PR.

### CODE REVIEW

**Comment by mbarkley** [comment]
@psiroky Has added Errai to the Jenkins PR job. Unfortunately there are test failures, but they seem unrelated to this change. Maybe @dgutierr could verify this?

This PR is now ready to be reviewed/merged.

**Comment by dgutierr** [comment]
ok to test

**Comment by csadilek** [comment]
@dgutierr test failures are unrelated to this change. I will go ahead and merge this so you don't run into problems tomorrow.

**Comment by csadilek** [comment]
+1

**Comment by csadilek** [comment]
master: 818a80a3071f7adfd7cd820bf3918d6fe65eae62

**Pull request closed without merging**
