### PR TITLE
AF-593+: Move dashbuilder-dataset to kie-soup.

### PR DESCRIPTION
**Pull request by mbarkley**
This PR moves most dashbuilder-dataset-* modules to kie-soup. The main reason for this PR is that several of these modules are dependencies of jbpm, so they cannot be part of the appformer repository which will need to be built after jbpm.

The only dataset module that could not be moved to kie-soup is the dashbuilder-dataset-cdi, which has dependencies on UberFire and Errai. But that module is not a dependency of any non-workbench module, so it can be moved to appformer.

### CODE REVIEW

**Comment by mbarkley** [comment]
Related:
https://github.com/kiegroup/kie-soup/pull/11
https://github.com/dashbuilder/dashbuilder/pull/393
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/597
https://github.com/kiegroup/jbpm/pull/1055
https://github.com/kiegroup/droolsjbpm-integration/pull/1257
https://github.com/kiegroup/kie-wb-common/pull/1275
https://github.com/kiegroup/drools-wb/pull/698
https://github.com/kiegroup/jbpm-wb/pull/937
https://github.com/kiegroup/optaplanner-wb/pull/236
https://github.com/kiegroup/kie-wb-distributions/pull/649

**Comment by mbarkley** [comment]
@dgutierr It's mostly just moving files, but would you mind reviewing this and the [kie-soup](https://github.com/kiegroup/kie-soup/pull/11) PR?

**Comment by manstis** [comment]
@dgutierr Please merge - I don't have permission - all other PRs merged.

**Comment by dgutierr** [comment]
Merged.

**Pull request closed without merging**
