### PR TITLE
CMS perspective fixes

### PR DESCRIPTION
**Pull request by dgutierr**
Fix + tests.

Depends on https://github.com/AppFormer/uberfire/pull/893

### CODE REVIEW

**Comment by dgutierr** [comment]
@kkufova can you review it please?

**Comment by kkufova** [comment]
jenkins execute full downstream build

**Comment by kkufova** [comment]
@dgutierr,
thanks for the fix, the renaming works much better now. However, I noticed that the renaming is not reflected if the page is used in some tree (and in the top menu): after you rename a page, the old name is still displayed in the **Navigation** panel and top menu. Could you please have a look at this as well?

**Comment by dgutierr** [comment]
@kkufova I think this is not an issue imho. Notice, we have two names:

1.- The name of the page an nav item is linked
2.- The nav item's display name

When the page is renamed the name of the nav items linked to that page are not changed. This is right, as the system must guarantee that the nav items names assigned by the user remains unchanged regardless of changes in the page names.

**Comment by dgutierr** [comment]
Jenkins execute full downstream build

**Comment by kkufova** [comment]
@dgutierr, you are completely right! I checked it one more time and you are right that the name set in the **Navigation** panel should stay the same regardless of renaming the page. Thanks, the fix works great!

**Comment by dgutierr** [comment]
@kkufova I added to the PR the AF-902 fix . Can you please also verify this so that both fixes are pushed together?

**Comment by kkufova** [comment]
@dgutierr, sure! I'll take a look.

While playing with the renaming, I noticed one thing: when you are editing a page in the Navigation panel and click the cross icon, the page is automatically renamed to `- New Page -` and it cannot be edited by clicking the edit icon anymore. I am not exactly sure what the cross should do, but I assume it should discard the latest changes. Could we maybe fix this bug in this PR as well, as it is basically a renaming issue?

**Comment by dgutierr** [comment]
@kkufova Sure, let me check...

**Comment by kkufova** [comment]
@dgutierr, alright, thank you, I'll check the permissions issue together with the fix for [DASHBUILDE-261](https://issues.jboss.org/browse/DASHBUILDE-261). I linked it with the [BPMSPL-786](https://issues.jboss.org/browse/BPMSPL-786) Jira. :-)

**Comment by dgutierr** [comment]
@kkufova Fixed DASHBUILDE-261.

Please have a look :-) ThanXs

**Comment by kkufova** [comment]
@dgutierr, everything works great with one exception: if you disable _update_ (but _create_ is enabled), it is not possible to save a page the user creates. I don't know how we should handle cases like that, I guess it doesn't make sense to for _update_ and _create_ to have one disabled and one enabled. Either we tie these two (only two cases: both disabled or both enabled), or we make sure that the pages the user creates can be saved (and possibly updated). WDYT?

**Comment by dgutierr** [comment]
Jenkins execute full downstream build

**Comment by dgutierr** [comment]
@kkufova Unfortunately, there is no support for single user permissions, so allowing users to update the pages they author, even though the "update" permission is not granted, it's not an option.

I agree the current implementation has some issues, but none of them are criticial imho. Forcing the "update" permission to be enabled if "create" is, could be an option. We can discuss about it. Thanks for the feedback :-)

**Pull request merged**
