### PR TITLE
DASHBUILDE-90: Missing argument functions fail in SQL datasets (0.4.x)

### PR DESCRIPTION
**Pull request by dgutierr**
Fix + tests

### CODE REVIEW

**Comment by dgutierr** [comment]
@romartin Can you please verify and merge?

**Comment by romartin** [comment]
Hi @dgutierr , I'm hitting with some compilation issues on some test classes and if fixing those, compilation errors when running the gwt compiler. Please can u rebase with latest HEAD? thx

**Comment by dgutierr** [comment]
@romartin Fixed.

**Comment by romartin** [comment]
@dgutierr +1. Thx! #7a77abedf2189b261ade292bd6c1273d97e201b2

**Pull request closed without merging**
