### PR TITLE
AF-546: Reduce startup time of AppFormer apps and workbenches

### PR DESCRIPTION
**Pull request by mbarkley**
Replace @AfterInitializations with @PostConstructs.
(Allows RPC calls to be combined into a single playload.)

### CODE REVIEW

**Comment by mbarkley** [comment]
Relates to:
* https://github.com/errai/errai/pull/267
* https://github.com/AppFormer/uberfire/pull/751
* https://github.com/kiegroup/guvnor/pull/464
* https://github.com/kiegroup/kie-wb-common/pull/937
* https://github.com/kiegroup/drools-wb/pull/533
* https://github.com/kiegroup/jbpm-form-modeler/pull/117
* https://github.com/kiegroup/kie-wb-distributions/pull/542
* https://github.com/kiegroup/optaplanner-wb/pull/181
* https://github.com/kiegroup/appformer/pull/88
* https://github.com/kiegroup/jbpm-wb/pull/764

**Comment by dgutierr** [comment]
The dashbuilder showcase does not work after these changes.. It throws an exception during client code initialization. See screenshots:

error1
error2

@mbarkley Any idea?

**Comment by mbarkley** [comment]
@dgutierr Did you build Errai and UberFire (branches in the linked PRs) before testing this?

I encountered that problem during development and it should be fixed.

**Comment by manstis** [comment]
@dgutierr Wainting for you to be happy before merging into _your_ repository.

**Comment by mbarkley** [comment]
@manstis @porcelli @dgutierr Looks like everyone has approved this now. Can one of you please merge?

**Pull request merged**
