### PR TITLE
DASHBUILDE-36: BS3 Upgrade fine tunning & bug fixing

### PR DESCRIPTION
**Pull request by romartin**
- Boolean Switch Editor - Refactor for using Toggle Switch BS3 (extras) component
- File Upload Editor - fixings for BS3 upgrade
- Data Set Editor
  - Refactor to BS3 grid system
  - Review tooltips (visibility and texts)
  - Columns and filter widgets fixings
  - Refactored disclosure panel for columns/filter panel
  - Column type updates reload the data set with new given column types (bug fixing)
  - Block an empty columns selection, at least one column must be selected
- Data Set Explorer
  - Some fixings and BS3 refactor upgrades
- Metric displayer
  - Visualization fixings
- New dashboard - Fixed bug for new perspective's menu entires (not visible)
- Displayer Editor
  - Refactor to BS3 grid system
  - Bug fixings
- Clean unused constants in dashbuilder-widgets

### CODE REVIEW

**Comment by dgutierr** [comment]
1. Timeframe function: combo year out of panel, month combo small, the text should not be trimmed.
bs3a

2. Expense reports=>Columns=>click en type selector arrow (column amount)=>layout gets crazy.
Can also be reproduced just by zooming out using  "Ctrl+mouse central wheel"
bs3b

3. CSV data set creation, click on upload icon without specifying a file. The loading icon never stops.
bs3c

4. Same as before with a file selected from local. UI shows error in file field and the "c:\fakepath\..." filename is shown as well.
bs3d

5. If columns names are large enough then overlap among them. This belongs to UFext table component, so we should file a JIRA there plus a JIRA in dashbuilder with t alink to the first one to keep track.
bs3e

6. Advanced tab

    * Zoom out=>layout turns into a bad state. I guess is due to BS3 layout system. It doesn't look well anyway.
    * Orange color OFF? I'm not sure, white text on grey background may be?
bs3f

7. Left panel, too much empty space. Previous impl was 220 px wifth. We need to figure out how to remove such empty space. The popup height is not fixed which causes the height to change depending on the popup content. Not sure if this looks well, I liked more the fixed height approach.
bs3g
bs3h

**Comment by romartin** [comment]
Both point 4 and 5 are reported as JIRA in UF. See:
- https://issues.jboss.org/browse/UF-222
- https://issues.jboss.org/browse/UF-223

Working on the other issues. Will update the PR when finished. Thx

**Comment by romartin** [comment]
All issues have been fixed. Try again please.

**Comment by dgutierr** [comment]
Reviewed & merged on master.

Great job Roger!

**Pull request closed without merging**
