### PR TITLE
[AF-549-dashbuilder]: Upgraded Elasticserch version to 5.6.1.

### PR DESCRIPTION
**Pull request by adrielparedes**
@dgutierr @romartin
Elasticsearch dataset upgraded to elasticsearch version 5.6.1

@psiroky just to confirm. Do we have docker into our servers?

### CODE REVIEW

**Comment by adrielparedes** [comment]
jenkins retest this

**Comment by romartin** [comment]
@psiroky so at this point, to run the tests for the Elastic Search stuff in dashbuilder, instead of running an standalone EL server process and running tests against it, it relies on having docker installed in the machine and it runs a container. It seems guvnor-ala relies on the docker deamon being present too, so I understand that now is a requirement having docker installed on the machine, is it? Just to double check. THanks!

**Comment by psiroky** [comment]
@romartion Yes, that seems to be the situation right now. Docker is installed on the jenkins slaves, so that should be an issue.

**Comment by romartin** [comment]
@psiroky  you mean "that should not be an issue", right? :) Anyway on the other hand at this point for running tests it's necessary to have docker installed (for all community users,etc)

**Comment by psiroky** [comment]
@romartin yes, should _not_ be an issue.

**Comment by adrielparedes** [comment]
@dgutierr @romartin who is in charge to merge this PR? :)

**Comment by dgutierr** [comment]
Merged.

**Pull request closed without merging**
