### PR TITLE
Upgrade jgit and sshd as required by UberFire

### PR DESCRIPTION
**Pull request by psiroky**

### CODE REVIEW

**Comment by psiroky** [comment]
See https://github.com/AppFormer/uberfire/commit/a4cf2e727c01a48fdf91ec5dd58f82dc1422913a

**Comment by psiroky** [comment]
Merging as we need this to fix the Docke CI containers.

**Comment by mbiarnes** [comment]
@psiroky I added a new job kie-docker-ci-images-7.2.x - do we need this change on dahsbuilder also 0.8.x?

**Comment by psiroky** [comment]
@mbiarnes no we don't. The upgrades in UF were only done on master.

**Pull request merged**
