### PR TITLE
upgraded jboss-ip-bom to 8.0.0.CR2

### PR DESCRIPTION
**Pull request by mbarkley**
This reverts commit 3cabbbd431d97a33033a6fd48d9c221e3943ca5e.

### CODE REVIEW

**Comment by mbarkley** [comment]
Related:
https://github.com/errai/errai/pull/307
https://github.com/kiegroup/kie-soup/pull/15
https://github.com/AppFormer/uberfire/pull/916
https://github.com/dashbuilder/dashbuilder/pull/409
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/615
https://github.com/kiegroup/drools-wb/pull/709

**Comment by mbarkley** [comment]
@dgutierr Almost certainly there will be test failures in dashbuilder-dataset-cdi. Some change in the arquillian/weld dependencies is causing an error where weld is not finding dependencies injected by the test classes.

**Comment by mbarkley** [comment]
@psiroky @dgutierr I'm not sure what's happening, but it looks to me like surefire is not running tests for dashbuilder-dataset-cdi in this PR build. It should be, and if it were we would see that those tests fail. Any ideas?

**Comment by psiroky** [comment]
@mbarkley Looking at the build results, at least some CDI tests seem to be there: https://kie-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/dashbuilder-pullrequests/505/testReport/org.dashbuilder.dataset/ . What specific tests are missing?

**Comment by mbarkley** [comment]
My mistake @psiroky. I was looking in the console logs and couldn't see where the tests ran, but should have just looked at the results.

Nonetheless, these tests still reliably fail for me locally with errors of "Unsatisfied dependencies" and I have no idea why this is different than the results on Jenkins.

**Pull request merged**
